camera_image_topic: /zed/zed_camera/rgb/image_rect_color
camera_info_topic: /zed/zed_camera/rgb/image_rect_color

charuco:
  squares_x: 14
  squares_y: 9
  square_length: 0.02
  marker_length: 0.015
  
workspace:
  x_min: -0.05
  x_max: 0.05
  y_min: -0.05
  y_max: 0.05
  z_min: -0.05
  z_max: 0.05
  rot_x_min: -5.0
  rot_x_max: 5.0
  rot_y_min: -5.0
  rot_y_max: 5.0
  rot_z_min: -5.0
  rot_z_max: 5.0

eef_start_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0] # [x,y,z,r,p,y]

eye_to_hand_calibration:
  num_samples: 25 # for debug purposes
  sample_delay: 0.4

eye_in_hand_calibration:
  num_samples: 25 # for debug purposes
  sample_delay: 0.4

