ARG ROS_DISTRO=humble
FROM ros:${ROS_DISTRO}-ros-base
MAINTAINER Peter David Fagan "peterdavidfagan@gmail.com"

# set default DDS to Cyclone
ENV ROS_DISTRO=humble
ENV RMW_IMPLEMENTATION rmw_cyclonedds_cpp

# install system dependencies
RUN apt-get update && \
    apt-get install -y neovim libxcb-cursor0 libgmp-dev python3-pip && \
    pip install pyqt6 dm_env envlogger[tfds] && \
    rm -rf /var/lib/apt/lists/*

# set up ROS workspace
ENV ROS_UNDERLAY /root/calibration_ws/install
WORKDIR $ROS_UNDERLAY/..
COPY moveit2_camera_calibration ./src/moveit2_camera_calibration

# set up workspace           
RUN . /opt/ros/${ROS_DISTRO}/setup.sh && \
    apt-get update && \
    apt-get install -y ros-${ROS_DISTRO}-rmw-cyclonedds-cpp ros-${ROS_DISTRO}-moveit && \
    rosdep update && \
    DEBIAN_FRONTEND=noninteractive \
    rosdep install --from-paths src --ignore-src -r -y --rosdistro ${ROS_DISTRO} && \
    colcon build && \
    rm -rf /var/lib/apt/lists/*

# create entrypoint
COPY .docker/ros_entrypoint.sh /sbin/ros_entrypoint.sh
RUN sudo chmod 755 /sbin/ros_entrypoint.sh
ENTRYPOINT ["/sbin/ros_entrypoint.sh"]
